collections: 
  types:
    output: true
  weapons: 
    output: true

defaults: 
  - scope: 
      path: ""
      type: "weapons"
    values:
      layout: "weapon"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: 
      path: ""
    values:
      layout: "default"